"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Charlie Luo"
email = "cvxluo@gmail.com"

# Default to showing my commits + remote tracking bookmarks in `jj log`
[revsets]
log = 'mine() | present(main@origin) | present(master@origin)'

# Shortcut to view all commits
[aliases]
log-all = ["log", "-r", "all()"]
# Move bookmarks from ancestor heads to the parent commit
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[templates]
git_push_bookmark = '"cvxluo/" ++ description.first_line().split(": ").last().lower().replace(" ", "-").substr(0, 50)'
